/*
 * Copyright 2026 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.jetsnack.model

import androidx.annotation.StringRes
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue
import com.example.jetsnack.R

/**
 * A real-scale 3D model of a snack, bundled in `assets/models` (generated by
 * `Jetsnack/ar/tools/generate-models.mjs`).
 *
 * @param assetPath glb path inside the app assets.
 * @param footprintMeters largest horizontal size of the model, used to lay snacks out on a table.
 * @param heightMeters height of the model, used to float labels above it.
 * @param customizable whether the model has the "Icing" / "Sprinkles" / "Drizzle" nodes driven by
 * [DonutStyle].
 */
@Immutable
data class SnackArModel(val assetPath: String, val footprintMeters: Float, val heightMeters: Float, val customizable: Boolean = false)

object SnackArModels {
    val Cupcake = SnackArModel("models/cupcake.glb", footprintMeters = 0.07f, heightMeters = 0.1f)
    val Donut = SnackArModel("models/donut.glb", footprintMeters = 0.104f, heightMeters = 0.035f, customizable = true)
    val Eclair = SnackArModel("models/eclair.glb", footprintMeters = 0.12f, heightMeters = 0.03f)
    val Gingerbread = SnackArModel("models/gingerbread.glb", footprintMeters = 0.13f, heightMeters = 0.012f)
    val IceCreamSandwich = SnackArModel("models/ice_cream_sandwich.glb", footprintMeters = 0.09f, heightMeters = 0.033f)
    val KitKat = SnackArModel("models/kitkat.glb", footprintMeters = 0.09f, heightMeters = 0.016f)

    val all = listOf(Cupcake, Donut, Eclair, Gingerbread, IceCreamSandwich, KitKat)
}

/** Icing flavors for the "Build your donut" customizer. Colors are linear RGB, as glTF expects. */
enum class DonutGlaze(@StringRes val label: Int, val linearColor: FloatArray, val drizzleLinearColor: FloatArray) {
    Strawberry(R.string.glaze_strawberry, floatArrayOf(0.9f, 0.24f, 0.5f), ChocolateDrizzle),
    Chocolate(R.string.glaze_chocolate, floatArrayOf(0.1f, 0.04f, 0.015f), VanillaDrizzle),
    Vanilla(R.string.glaze_vanilla, floatArrayOf(0.95f, 0.9f, 0.78f), ChocolateDrizzle),
    Matcha(R.string.glaze_matcha, floatArrayOf(0.3f, 0.5f, 0.12f), VanillaDrizzle),
}

private val ChocolateDrizzle = floatArrayOf(0.12f, 0.05f, 0.02f)
private val VanillaDrizzle = floatArrayOf(0.96f, 0.94f, 0.9f)

@Immutable
data class DonutStyle(val glaze: DonutGlaze = DonutGlaze.Strawberry, val sprinkles: Boolean = true, val drizzle: Boolean = false)

/**
 * The donut the user is building. Shared by the snack detail 3D viewer and the AR screen so a
 * customized donut is the one placed on the table.
 */
object DonutStyleRepo {
    var style by mutableStateOf(DonutStyle())
}
